//! /commit_message — Generate a conventional commit message for the PR's changes.

use async_trait::async_trait;
use tracing::info;

use super::{MerlinTool, ToolContext};
use crate::diff::parse_diff;
use crate::error::Result;

pub struct CommitMessageTool;

#[async_trait]
impl MerlinTool for CommitMessageTool {
    fn name(&self) -> &'static str {
        "commit_message"
    }

    async fn run(&self, ctx: &ToolContext) -> Result<String> {
        info!("Running /commit_message");

        let raw_diff = ctx.platform.get_diff().await?;
        let pr_info = ctx.platform.get_pr_info().await?;
        let files = parse_diff(&raw_diff)?;

        let file_list: Vec<String> = files.iter().map(|f| format!("`{}`", f.path())).collect();

        let system = "You are an expert at writing Conventional Commits (https://conventionalcommits.org).\n\n\
                      Generate 3 commit message options for the squash merge of this PR, in order from \
                      most to least specific. Each must follow:\n\
                        <type>(<optional scope>): <description>\n\
                        [optional body]\n\
                        [optional footer: Closes #N]\n\n\
                      Types: feat, fix, refactor, test, docs, style, perf, chore, ci\n\n\
                      Respond with JSON:\n\
                      {\"options\": [{\"message\": \"feat(auth): add JWT refresh token rotation\", \
                      \"type\": \"feat\", \"scope\": \"auth\", \"breaking\": false}]}";

        let user = format!(
            "PR #{num}: \"{title}\" by @{author}\n\nFiles ({n}):\n{files}",
            num = pr_info.number,
            title = pr_info.title,
            author = pr_info.author,
            n = files.len(),
            files = file_list.join("\n"),
        );

        let raw = ctx.ai.generate(system, &user).await?;
        let cleaned = raw
            .trim()
            .trim_start_matches("```json")
            .trim_start_matches("```")
            .trim_end_matches("```")
            .trim();

        let value: serde_json::Value =
            serde_json::from_str(cleaned).unwrap_or_else(|_| serde_json::json!({"options": []}));

        let mut out = "## Merlin: Commit Message Options\n\n".to_string();
        out.push_str("Choose one of these conventional commit messages for the squash merge:\n\n");

        if let Some(options) = value["options"].as_array() {
            for (i, opt) in options.iter().enumerate() {
                let msg = opt["message"].as_str().unwrap_or("");
                let breaking = opt["breaking"].as_bool().unwrap_or(false);
                let breaking_note = if breaking { " ⚠️ **BREAKING CHANGE**" } else { "" };
                out.push_str(&format!(
                    "**Option {}**{breaking_note}:\n```\n{msg}\n```\n\n",
                    i + 1
                ));
            }
        } else {
            out.push_str(&format!("```\n{raw}\n```\n\n"));
        }

        out.push_str("*Generated by [Merlin](https://github.com/you/merlin) 🦡*");
        Ok(out)
    }
}
