//! /docs — Comprehensive documentation generator.
//!
//! Generates multiple documentation artifacts from the codebase:
//!   - Module-level documentation
//!   - API documentation (Markdown)
//!   - README sections
//!   - Architecture decision records (ADRs)
//!   - Inline docstring suggestions
//!
//! Usage:
//!   @merlin /docs              — auto-detect and generate all docs
//!   @merlin /docs readme       — generate/update README section
//!   @merlin /docs api          — generate API reference
//!   @merlin /docs adr          — generate Architecture Decision Record
//!   @merlin /docs module       — generate module-level docs
//!   @merlin /docs wiki         — generate a wiki-style page

use async_trait::async_trait;
use tracing::info;

use super::{MerlinTool, ToolContext};
use crate::diff::parse_diff;
use crate::error::Result;

pub struct DocsTool;

/// The kind of documentation to generate.
#[derive(Debug, Clone, PartialEq)]
enum DocsMode {
    Auto,
    Readme,
    Api,
    Adr,
    Module,
    Wiki,
}

impl DocsMode {
    fn from_arg(arg: Option<&str>) -> Self {
        match arg.map(|s| s.trim().to_lowercase()).as_deref() {
            Some("readme") => DocsMode::Readme,
            Some("api") => DocsMode::Api,
            Some("adr") => DocsMode::Adr,
            Some("module") => DocsMode::Module,
            Some("wiki") => DocsMode::Wiki,
            _ => DocsMode::Auto,
        }
    }
}

#[async_trait]
impl MerlinTool for DocsTool {
    fn name(&self) -> &'static str {
        "docs"
    }

    async fn run(&self, ctx: &ToolContext) -> Result<String> {
        info!("Running /docs");

        let mode = DocsMode::from_arg(ctx.arg.as_deref());
        let raw_diff = ctx.platform.get_diff().await?;
        let pr_info = ctx.platform.get_pr_info().await?;
        let files = parse_diff(&raw_diff)?;

        // For auto mode, generate all applicable doc types
        let result = match mode {
            DocsMode::Readme => generate_readme(ctx, &pr_info, &files).await?,
            DocsMode::Api => generate_api_docs(ctx, &pr_info, &files).await?,
            DocsMode::Adr => generate_adr(ctx, &pr_info, &files).await?,
            DocsMode::Module => generate_module_docs(ctx, &pr_info, &files).await?,
            DocsMode::Wiki => generate_wiki(ctx, &pr_info, &files).await?,
            DocsMode::Auto => generate_auto(ctx, &pr_info, &files).await?,
        };

        Ok(result)
    }
}

// ── Auto mode ─────────────────────────────────────────────────────────────────

async fn generate_auto(
    ctx: &ToolContext,
    pr_info: &crate::platform::PrInfo,
    files: &[crate::diff::FileDiff],
) -> Result<String> {
    let system = "You are a technical documentation expert. \
                  Analyze the PR and generate the most appropriate documentation. \
                  Choose from: module docs, API reference, or README updates. \
                  Produce clean, developer-friendly Markdown. \
                  Start with a brief statement of what documentation type you chose and why.";

    let file_summary = files
        .iter()
        .map(|f| format!("- `{}` ({} hunk(s))", f.path(), f.hunks.len()))
        .collect::<Vec<_>>()
        .join("\n");

    let diff_preview = files
        .iter()
        .take(5)
        .map(|f| crate::digest::compress_diff(f, 40))
        .collect::<Vec<_>>()
        .join("\n\n");

    let user = format!(
        "PR #{num}: \"{title}\"\n\nChanged files:\n{files}\n\nDiff preview:\n{diff}",
        num = pr_info.number,
        title = pr_info.title,
        files = file_summary,
        diff = diff_preview,
    );

    let docs = ctx.ai.generate(system, &user).await?;
    Ok(format!(
        "## Merlin: Documentation\n\n{docs}\n\n\
         *Generated by [Merlin](https://github.com/you/merlin) 🦡*"
    ))
}

// ── README generator ──────────────────────────────────────────────────────────

async fn generate_readme(
    ctx: &ToolContext,
    pr_info: &crate::platform::PrInfo,
    files: &[crate::diff::FileDiff],
) -> Result<String> {
    let system = "You are a technical writer. Generate a README.md section for the feature \
                  or change introduced by this PR. Include:\n\
                  - Feature name as H2 heading\n\
                  - Description (2-3 sentences)\n\
                  - Usage example with code block\n\
                  - Configuration options (if any)\n\
                  - Any prerequisites or notes\n\
                  Write in the style of a professional open-source project README.";

    let diff_text = files
        .iter()
        .map(|f| crate::digest::compress_diff(f, 50))
        .collect::<Vec<_>>()
        .join("\n\n");

    let user = format!(
        "PR: \"{title}\"\n\nCode changes:\n{diff}",
        title = pr_info.title,
        diff = diff_text,
    );

    let section = ctx.ai.generate(system, &user).await?;

    // Offer to append to README
    let existing = ctx.platform.get_file("README.md").await.ok().flatten();
    let readme_action = if let Some((content, sha)) = existing {
        let updated = format!("{}\n\n{}", content.trim_end(), section.trim());
        let _ = ctx
            .platform
            .update_file(
                "README.md",
                &updated,
                &format!("docs: update README for PR #{}", pr_info.number),
                Some(&sha),
            )
            .await;
        "README.md has been updated with the new section."
    } else {
        "*(README.md not found — copy the section below into your README)*"
    };

    Ok(format!(
        "## Merlin: README Section\n\n{readme_action}\n\n---\n\n{section}\n\n\
         *Generated by [Merlin](https://github.com/you/merlin) 🦡*"
    ))
}

// ── API documentation ─────────────────────────────────────────────────────────

async fn generate_api_docs(
    ctx: &ToolContext,
    pr_info: &crate::platform::PrInfo,
    files: &[crate::diff::FileDiff],
) -> Result<String> {
    let system = "You are an API documentation specialist. Generate a Markdown API reference \
                  for the public functions, types, and interfaces introduced or modified in this PR.\n\n\
                  For each public item produce:\n\
                  ## `function_name(param: Type) -> ReturnType`\n\
                  Description of what it does.\n\
                  **Parameters:**\n- `param` — what it is\n\
                  **Returns:** What is returned\n\
                  **Example:**\n```language\ncode example\n```\n\n\
                  Only document public/exported items. Skip private helpers.";

    let diff_text = files
        .iter()
        .map(|f| {
            format!(
                "### `{}`\n```diff\n{}\n```",
                f.path(),
                crate::digest::compress_diff(f, 80)
            )
        })
        .collect::<Vec<_>>()
        .join("\n\n");

    let user = format!(
        "PR: \"{title}\"\n\nChanged files:\n{diff}",
        title = pr_info.title,
        diff = diff_text,
    );

    let api_docs = ctx.ai.generate(system, &user).await?;

    Ok(format!(
        "## Merlin: API Documentation\n\n{api_docs}\n\n\
         *Generated by [Merlin](https://github.com/you/merlin) 🦡*"
    ))
}

// ── Architecture Decision Record ──────────────────────────────────────────────

async fn generate_adr(
    ctx: &ToolContext,
    pr_info: &crate::platform::PrInfo,
    files: &[crate::diff::FileDiff],
) -> Result<String> {
    let system = "You are a software architect. Generate an Architecture Decision Record (ADR) \
                  in the Nygard format for the design decision represented by this PR.\n\n\
                  Use this exact structure:\n\
                  # ADR-XXXX: Title\n\
                  **Date:** YYYY-MM-DD\n\
                  **Status:** Proposed\n\n\
                  ## Context\n[What is the issue motivating this decision?]\n\n\
                  ## Decision\n[What is the change being proposed?]\n\n\
                  ## Consequences\n### Positive\n- ...\n### Negative\n- ...\n### Neutral\n- ...\n\n\
                  ## Alternatives Considered\n[What else was considered?]";

    let diff_text = files
        .iter()
        .take(8)
        .map(|f| crate::digest::compress_diff(f, 40))
        .collect::<Vec<_>>()
        .join("\n\n");

    let user = format!(
        "PR #{num}: \"{title}\" by @{author}\n\nDescription: {body}\n\nDiff:\n{diff}",
        num = pr_info.number,
        title = pr_info.title,
        author = pr_info.author,
        body = pr_info.body.chars().take(500).collect::<String>(),
        diff = diff_text,
    );

    let adr = ctx.ai.generate(system, &user).await?;

    // Optionally write to docs/adr/ directory
    let adr_path = format!("docs/adr/adr-pr{}.md", pr_info.number);
    let _ = ctx
        .platform
        .update_file(&adr_path, &adr, "docs: add ADR", None)
        .await;

    Ok(format!(
        "## Merlin: Architecture Decision Record\n\nWritten to `{adr_path}`:\n\n---\n\n{adr}\n\n\
         *Generated by [Merlin](https://github.com/you/merlin) 🦡*"
    ))
}

// ── Module documentation ──────────────────────────────────────────────────────

async fn generate_module_docs(
    ctx: &ToolContext,
    pr_info: &crate::platform::PrInfo,
    files: &[crate::diff::FileDiff],
) -> Result<String> {
    let system = "You are a documentation expert. Generate module-level documentation comments \
                  for each changed source file. For each file produce:\n\
                  - A module docstring (in the appropriate language syntax: //!, ///, #\"\"\", etc.)\n\
                  - Brief overview of the module's responsibility\n\
                  - Key types/functions exported\n\
                  - Usage example\n\n\
                  Return as JSON: [{\"file\":\"path\",\"docstring\":\"...\"}]";

    let diff_text = files
        .iter()
        .map(|f| {
            format!(
                "File: {}\n{}",
                f.path(),
                crate::digest::compress_diff(f, 60)
            )
        })
        .collect::<Vec<_>>()
        .join("\n\n");

    let raw = ctx.ai.generate(system, &diff_text).await?;
    let cleaned = raw
        .trim()
        .trim_start_matches("```json")
        .trim_start_matches("```")
        .trim_end_matches("```")
        .trim();

    let modules: Vec<serde_json::Value> = serde_json::from_str(cleaned).unwrap_or_default();

    let mut out = format!(
        "## Merlin: Module Documentation\n\nFor PR \"{}\"\n\n",
        pr_info.title
    );

    for m in &modules {
        let file = m["file"].as_str().unwrap_or("unknown");
        let doc = m["docstring"].as_str().unwrap_or("");
        let ext = file.rsplit('.').next().unwrap_or("text");
        out.push_str(&format!("### `{file}`\n\n```{ext}\n{doc}\n```\n\n"));
    }

    out.push_str("*Generated by [Merlin](https://github.com/you/merlin) 🦡*");
    Ok(out)
}

// ── Wiki page generator ───────────────────────────────────────────────────────

async fn generate_wiki(
    ctx: &ToolContext,
    pr_info: &crate::platform::PrInfo,
    files: &[crate::diff::FileDiff],
) -> Result<String> {
    let system = "You are a technical writer creating a wiki page for a software feature. \
                  Write a comprehensive, well-structured wiki page in Markdown that covers:\n\
                  - Overview and purpose\n\
                  - How it works (with diagrams described in text/ASCII if helpful)\n\
                  - Configuration and setup\n\
                  - Usage examples\n\
                  - Troubleshooting\n\
                  - Related pages (suggest titles, not URLs)\n\
                  Write for a developer audience that's new to this feature.";

    let file_list = files
        .iter()
        .map(|f| f.path())
        .collect::<Vec<_>>()
        .join(", ");
    let diff_preview = files
        .iter()
        .take(5)
        .map(|f| crate::digest::compress_diff(f, 40))
        .collect::<Vec<_>>()
        .join("\n\n");

    let user = format!(
        "PR #{num}: \"{title}\"\nDescription: {body}\nFiles: {files}\n\nDiff:\n{diff}",
        num = pr_info.number,
        title = pr_info.title,
        body = pr_info.body.chars().take(400).collect::<String>(),
        files = file_list,
        diff = diff_preview,
    );

    let wiki = ctx.ai.generate(system, &user).await?;

    Ok(format!(
        "## Merlin: Wiki Page\n\n{wiki}\n\n\
         *Generated by [Merlin](https://github.com/you/merlin) 🦡*"
    ))
}
