//! /spec — Generate a comprehensive technical specification and update the PR description.
//!
//! Produces a detailed, structured Markdown document covering:
//!   - Problem statement & motivation
//!   - Technical approach and design decisions
//!   - Component-by-component change breakdown
//!   - API / data-model changes
//!   - Testing strategy
//!   - Rollout & deployment notes
//!   - Open questions
//!
//! The generated spec replaces the PR description so reviewers have full context
//! before reading a single line of code.

use async_trait::async_trait;
use tracing::info;

use super::{MerlinTool, ToolContext};
use crate::diff::parse_diff;
use crate::digest::compress_diff;
use crate::error::Result;

pub struct SpecTool;

#[async_trait]
impl MerlinTool for SpecTool {
    fn name(&self) -> &'static str {
        "spec"
    }

    async fn run(&self, ctx: &ToolContext) -> Result<String> {
        info!("Running /spec");

        let raw_diff = ctx.platform.get_diff().await?;
        let pr_info = ctx.platform.get_pr_info().await?;
        let files = parse_diff(&raw_diff)?;

        // Build a compact diff summary (each file capped to avoid token overflow)
        let diff_summary = files
            .iter()
            .map(|f| compress_diff(f, 60))
            .collect::<Vec<_>>()
            .join("\n\n---\n\n");

        let file_list = files
            .iter()
            .map(|f| {
                let tag = if f.is_new {
                    " *(new)*"
                } else if f.is_deleted {
                    " *(deleted)*"
                } else {
                    ""
                };
                format!("- `{}`{tag}", f.path())
            })
            .collect::<Vec<_>>()
            .join("\n");

        let stats = format!(
            "{} file(s) changed — +{} / -{} lines",
            pr_info.files_changed, pr_info.additions, pr_info.deletions,
        );

        let system = "\
You are a principal engineer writing an internal technical specification for a pull request. \
Your specification will be set as the PR description so ALL reviewers see it before reading \
any code. Be precise, concrete, and thorough.

Write ONLY valid Markdown — no prose outside the spec, no preamble. \
Use the exact section headings listed in the user prompt.";

        let user = format!(
            r#"Generate a technical specification for the following pull request.

## PR Metadata
- **Title:** {title}
- **Author:** {author}
- **Base branch:** `{base}` ← `{head}`
- **Stats:** {stats}
- **Labels:** {labels}

## Existing description (may be empty or a placeholder)
{existing_body}

## Files changed
{file_list}

## Diff
```diff
{diff}
```

---

Produce a Markdown document with EXACTLY these sections (add sub-sections as needed):

# {title}

## Overview
One paragraph. What does this PR do and why does it exist?

## Problem Statement
What problem, bug, or product requirement motivated this change?

## Technical Approach
How was the problem solved? Mention key design decisions, patterns, trade-offs, and alternatives considered.

## Changes
A component-by-component breakdown. For each logical group of files, explain what changed and why.

## API Changes
List any changes to public interfaces, REST endpoints, CLI flags, config keys, or exported types.
Write "None" if there are no API changes.

## Data Model Changes
Any changes to database schemas, struct layouts, serialisation formats, or file formats.
Write "None" if not applicable.

## Dependencies
New, removed, or version-bumped dependencies and the reason for each.
Write "None" if no dependencies changed.

## Testing Strategy
How should a reviewer verify this works? Include unit tests, integration tests, manual steps, and edge cases.

## Rollout & Deployment Notes
Feature flags, migration steps, backward-compatibility concerns, environment variables required, or anything ops needs to know.
Write "None" if this is a straightforward deployment.

## Open Questions
Unresolved decisions, follow-up work, or things the author explicitly wants reviewer input on.
Write "None" if there are no open questions.

---
*Generated by [Merlin](https://github.com/Arunachalamkalimuthu/merlin-ai-code-review) 🧙*
"#,
            title = pr_info.title,
            author = pr_info.author,
            base = pr_info.base_branch,
            head = pr_info.head_branch,
            stats = stats,
            labels = if pr_info.labels.is_empty() {
                "none".to_string()
            } else {
                pr_info.labels.join(", ")
            },
            existing_body = if pr_info.body.trim().is_empty() {
                "*(no description)*".to_string()
            } else {
                pr_info.body.clone()
            },
            file_list = file_list,
            diff = diff_summary,
        );

        let spec = ctx.ai.generate(system, &user).await?;

        // Derive an improved title from the first H1 line if the AI rewrote it,
        // otherwise keep the existing PR title.
        let new_title = spec
            .lines()
            .find(|l| l.starts_with("# "))
            .map(|l| l.trim_start_matches("# ").trim().to_string())
            .filter(|t| !t.is_empty())
            .unwrap_or_else(|| pr_info.title.clone());

        // Strip the H1 from the body (GitHub renders the PR title separately)
        let body_without_h1 = spec
            .lines()
            .skip_while(|l| l.starts_with("# "))
            .collect::<Vec<_>>()
            .join("\n")
            .trim_start()
            .to_string();

        ctx.platform
            .update_description(&new_title, &body_without_h1)
            .await?;

        info!("PR description updated with technical specification");

        Ok(format!(
            "## Merlin: Technical Specification Generated\n\n\
             The PR description has been updated with a full technical spec.\n\n\
             **Title:** {new_title}\n\n\
             ---\n\n\
             {body_without_h1}"
        ))
    }
}

#[cfg(test)]
mod tests {
    #[test]
    fn spec_tool_name() {
        use super::super::MerlinTool;
        assert_eq!(super::SpecTool.name(), "spec");
    }
}
