//! /test — AI-powered unit test generation for changed code.
//!
//! Generates tests for every new or modified function/method in the diff.
//! Detects the test framework from project files and generates idiomatic tests.

use async_trait::async_trait;
use tracing::info;

use super::{MerlinTool, ToolContext};
use crate::diff::{parse_diff, LineKind};
use crate::error::Result;

/// Tool for the `/test` slash command — generates unit tests for changed code.
pub struct TestGenTool;

#[async_trait]
impl MerlinTool for TestGenTool {
    fn name(&self) -> &'static str {
        "test"
    }

    async fn run(&self, ctx: &ToolContext) -> Result<String> {
        info!("Running /test");

        let raw_diff = ctx.platform.get_diff().await?;
        let pr_info = ctx.platform.get_pr_info().await?;
        let files = parse_diff(&raw_diff)?;

        // Only review files with added lines
        let changed: Vec<_> = files
            .iter()
            .filter(|f| {
                !is_test_file(f.path())
                    && f.hunks
                        .iter()
                        .any(|h| h.lines.iter().any(|l| l.kind == LineKind::Added))
            })
            .collect();

        if changed.is_empty() {
            return Ok(
                "## Merlin: Test Generation\n\nNo new or modified source files detected."
                    .to_string(),
            );
        }

        let system = "You are an expert in test-driven development. \
                      Generate comprehensive unit tests for the changed code. \
                      Detect the language and testing framework from the file extension and imports \
                      (Rust→#[test], Python→pytest, JS/TS→Jest, Java→JUnit, Go→testing, etc.).\n\n\
                      For each changed function/method generate:\n\
                      - Happy path tests\n\
                      - Edge case tests (empty, nil/null, boundary values)\n\
                      - Error/exception path tests\n\n\
                      Return a JSON array:\n\
                      [{\"file\":\"src/foo_test.rs\",\"language\":\"rust\",\
                      \"code\":\"#[cfg(test)]\\nmod tests { ... }\",\
                      \"functions_tested\":[\"foo\",\"bar\"]}]\n\
                      Return [] if no testable functions are found.";

        let mut all_test_blocks: Vec<serde_json::Value> = Vec::new();
        let mut summary_lines: Vec<String> = Vec::new();

        for file in &changed {
            let diff_text = crate::digest::compress_diff(file, 150);
            let user = format!(
                "Generate tests for the new/modified code in `{}`:\n\n```diff\n{}\n```",
                file.path(),
                diff_text
            );

            let raw = ctx.ai.generate(system, &user).await.unwrap_or_default();
            let cleaned = raw
                .trim()
                .trim_start_matches("```json")
                .trim_start_matches("```")
                .trim_end_matches("```")
                .trim();

            if let Ok(blocks) = serde_json::from_str::<Vec<serde_json::Value>>(cleaned) {
                for block in &blocks {
                    let test_file = block["file"].as_str().unwrap_or("unknown_test");
                    let fns = block["functions_tested"]
                        .as_array()
                        .map(|a| {
                            a.iter()
                                .filter_map(|v| v.as_str())
                                .collect::<Vec<_>>()
                                .join(", ")
                        })
                        .unwrap_or_default();
                    summary_lines.push(format!("- `{test_file}` — tests for: {fns}"));
                    all_test_blocks.push(block.clone());
                }
            }
        }

        if all_test_blocks.is_empty() {
            return Ok(format!(
                "## Merlin: Test Generation\n\nAnalyzed {} file(s) for PR \"{}\". \
                 No directly testable functions detected in the changed code.",
                changed.len(),
                pr_info.title
            ));
        }

        // Format test blocks as a fenced-code comment for review
        let mut out = format!(
            "## Merlin: Generated Tests\n\nGenerated tests for **{}** file(s) in PR \"{}\":\n\n{}\n\n",
            all_test_blocks.len(),
            pr_info.title,
            summary_lines.join("\n")
        );

        for block in &all_test_blocks {
            let test_file = block["file"].as_str().unwrap_or("test_file");
            let language = block["language"].as_str().unwrap_or("text");
            let code = block["code"].as_str().unwrap_or("");
            out.push_str(&format!(
                "### `{test_file}`\n\n```{language}\n{code}\n```\n\n"
            ));
        }

        out.push_str(
            "> Copy these tests into your test files and adjust imports as needed.\n\n\
             *Generated by [Merlin](https://github.com/you/merlin) 🦡*",
        );
        Ok(out)
    }
}

fn is_test_file(path: &str) -> bool {
    let lower = path.to_lowercase();
    lower.contains("test") || lower.contains("spec") || lower.ends_with("_test.go")
}
